// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-epCYJtLw4xSBDIRzShhdu349rkjDYxg',
    appId: '1:530402102237:web:f6e4240cd1c99478a10434',
    messagingSenderId: '530402102237',
    projectId: 'edumate-college',
    authDomain: 'edumate-college.firebaseapp.com',
    storageBucket: 'edumate-college.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJoI0ZRHGMM6d8E_zWBqLIFSJH8EB8ehE',
    appId: '1:530402102237:android:6d32703c1261f49ea10434',
    messagingSenderId: '530402102237',
    projectId: 'edumate-college',
    storageBucket: 'edumate-college.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcSpHovH_gOxqJ_5FXzZYpLLO6EcfvBKo',
    appId: '1:530402102237:ios:2e7d24310ae8fa29a10434',
    messagingSenderId: '530402102237',
    projectId: 'edumate-college',
    storageBucket: 'edumate-college.firebasestorage.app',
    iosClientId: '530402102237-j97park63bs1q0u9l0rp1jlrsb5ups4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.edumate',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcSpHovH_gOxqJ_5FXzZYpLLO6EcfvBKo',
    appId: '1:530402102237:ios:2e7d24310ae8fa29a10434',
    messagingSenderId: '530402102237',
    projectId: 'edumate-college',
    storageBucket: 'edumate-college.firebasestorage.app',
    iosClientId: '530402102237-j97park63bs1q0u9l0rp1jlrsb5ups4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.edumate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-epCYJtLw4xSBDIRzShhdu349rkjDYxg',
    appId: '1:530402102237:web:4d68b187f4f635d1a10434',
    messagingSenderId: '530402102237',
    projectId: 'edumate-college',
    authDomain: 'edumate-college.firebaseapp.com',
    storageBucket: 'edumate-college.firebasestorage.app',
  );
}
